### ISSUE TITLE
 AttributeError: 'StarDist3D' object has no attribute '_tile_overlap'

### ISSUE THREAD

**Issue by orena1** [JaneliaSciComp/multifish#24]
## Bug report 
I get this error when trying to run the pipelline
```cmd
  2022-09-12 07:32:41.066691: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
  Relying on driver to perform ptx compilation. This message will be only logged once.
  2022-09-12 07:32:41.129963: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
  2022-09-12 07:34:17.501902: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
  Traceback (most recent call last):
    File "/miniconda/lib/python3.6/site-packages/stardist/models/base.py", line 684, in _axes_tile_overlap
      self._tile_overlap
  AttributeError: 'StarDist3D' object has no attribute '_tile_overlap'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/app/segmentation/scripts/starfinity_prediction.py", line 40, in <module>
      verbose=True)
    File "/miniconda/lib/python3.6/site-packages/stardist/models/base.py", line 564, in predict_instances
      **predict_kwargs)
    File "/miniconda/lib/python3.6/site-packages/stardist/models/base.py", line 298, in predict
      axes_net_tile_overlaps = self._axes_tile_overlap(axes_net)
    File "/miniconda/lib/python3.6/site-packages/stardist/models/base.py", line 686, in _axes_tile_overlap
      self._tile_overlap = self._compute_receptive_field()
    File "/miniconda/lib/python3.6/site-packages/stardist/models/base.py", line 671, in _compute_receptive_field
      y  = self.keras_model.predict([x,x])[0][0,...,0]
    File "/miniconda/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
      callbacks=callbacks)
    File "/miniconda/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
      batch_outs = f(ins_batch)
    File "/miniconda/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
      run_metadata=self.run_metadata)
    File "/miniconda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
      run_metadata_ptr)
  tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
    (0) Internal: Blas SGEMM launch failed : m=262144, n=1, k=128
         [[{{node prob/convolution}}]]
         [[prob/Sigmoid/_183]]
    (1) Internal: Blas SGEMM launch failed : m=262144, n=1, k=128
         [[{{node prob/convolution}}]]
  0 successful operations.
  0 derived errors ignored.

Work dir:
  /home/andermannlab/Downloads/multifish/work/01/8661203d74ec165bb0439af0a136c8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh
```
## Description of the problem

I am trying to run the example data pipeline as follows:
`./examples/demo_tiny.sh /mnt/ssd_cache/ezfish_sample`
and I get an the error above, specifically:
`  AttributeError: 'StarDist3D' object has no attribute '_tile_overlap'` which feels like a version problem of stardist, but AFAIU all versions should be identical to the pipeline verisons.

## Log file(s)

(Please attach relevant log files, including .nextflow.log and any process logs that had errors.)

### Environment 

* EASI-FISH Pipeline version: [?] 
* Nextflow version: `N E X T F L O W  ~  version 22.04.5`
* Container runtime: `Launching `./main.nf` [cranky_ride] DSL2 - revision: 797a91dda`
* Platform: `Local ubuntu 20.04`
* Operating system: `Linux`

**Comment by krokicki** [comment]
Hi @orena1 ,

So far, we can't reproduce this issue. It's not entirely clear, but possibly the root error is "failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED", and has something to do with CUDA support for the Stardist tool. 

Could you please provide some more information:
1) What version of Singularity are you using? 
2) Are you running on host with a GPU? If so, can you attach the output of `nvidia-smi --list-gpus` and/or `glxinfo`? 
3) Please attach your /home/andermannlab/Downloads/multifish/work/01/.command.log file

It might also be worth cross-posting this at https://github.com/stardist/stardist, and you could also refer to https://docs.sylabs.io/guides/3.5/user-guide/gpu.html to see if there's something there related to your particular GPU setup. 

Best regards,
Konrad

**Comment by orena1** [comment]
Thanks, if I'll use the full pipeline again I'll post, thanks.
